# Generated by Django 3.2.5 on 2022-02-10 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='iso',
            old_name='name',
            new_name='iso',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='name',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='name',
            new_name='state',
        ),
    ]
