# Generated by Django 3.2.5 on 2022-02-10 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0002_auto_20220210_0149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='iso',
            old_name='iso',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='region',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='state',
            new_name='name',
        ),
    ]
